// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8s-U1ZJfquBuP9sxwyz4_8yRTPQ4FOI',
    appId: '1:901075282077:web:d07022a7eb709e90668c74',
    messagingSenderId: '901075282077',
    projectId: 'fir-auth-a886a',
    authDomain: 'fir-auth-a886a.firebaseapp.com',
    databaseURL: 'https://fir-auth-a886a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-a886a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_SxpQBXwZlAK4FotDrY058BPFYyoaFPw',
    appId: '1:901075282077:android:314f462f1587a70e668c74',
    messagingSenderId: '901075282077',
    projectId: 'fir-auth-a886a',
    databaseURL: 'https://fir-auth-a886a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-a886a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbwHTeB4LiD19K5fUF99MYx46j_jlErO0',
    appId: '1:901075282077:ios:02fe2e9b9cd53179668c74',
    messagingSenderId: '901075282077',
    projectId: 'fir-auth-a886a',
    databaseURL: 'https://fir-auth-a886a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-a886a.appspot.com',
    iosBundleId: 'com.codexia.moneyWatcher',
  );
}
